# Generated by Django 5.1.4 on 2026-03-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='leetcode_handle',
        ),
    ]
